version: '3'
services:
  postgres:
    image: postgres:15
    container_name: strapi-db
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  strapi:
    build: .
    container_name: strapi-app
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_pass
      DATABASE_SSL: false
    ports:
      - "1337:1337"
    volumes:
      - ./app:/app
    command: ["npm", "run", "start"]

volumes:
  pg_data: